inherit_from: 
  - https://raw.githubusercontent.com/hintmedia/hint_style_config/master/.hint_rubocop.yml
  - .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 4.2
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'app/models/concerns/rails_admin/*'
    - 'app/one_time_jobs/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile*'
    - 'script/**/*'
    - 'test/**/*'
    - 'vendor/**/*'

# Limit line length
Metrics/LineLength:
  Max: 12000

Style/EmptyMethod:
  EnforcedStyle: expanded
  Enabled: true
  
